development:
  adapter: mysql
  database: rails_development
  host: localhost
  username: root
  password: 

test:
  adapter: mysql
  database: rails_test
  host: localhost
  username: root
  password:

production:
  adapter: mysql
  database: railsday3
  host: railsday.com
  username: user64115
  password: 1006
